apiVersion: apps/v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  type: clusterIP
  selector:
    name: redis-pod
    app: demo-voting-app
  ports: # a nodePort is not needed becasue this is for an internal service
      - port: 6379
        targetPort: 6379
  